'use client'

import '@lunagraph/editor/styles.css';
import { LunagraphEditor, LUCIDE_PROPS_SCHEMA, type FEElement } from "@lunagraph/editor";
import * as lunagraph from '../../.lunagraph/components';
// Import snapshots - generated by `lunagraph generate-snapshots`
import { snapshots, internalComponents } from '../../.lunagraph/snapshots';
// Import snapshot metadata for read-only mode (enables double-click to view component structure)
import snapshotMetadata from '../../.lunagraph/snapshots/metadata.json';

// Import pages manifest - auto-generated by dev-server when pages are created/saved
import pagesManifest from '../../.lunagraph/pages.json'

// Import Lucide icons
import * as LucideIcons from "lucide-react";

export default function Editor() {
  return (
    <LunagraphEditor
      {...lunagraph}
      components={{ ...lunagraph.components, ...internalComponents }}
      snapshots={snapshots}
      snapshotMetadata={snapshotMetadata}
      initialPages={pagesManifest.pages as Array<{ id: string; name: string; elements: FEElement[] }>}
      iconLibraries={{
        "lucide-react": {
          icons: LucideIcons,
          displayName: "Lucide",
          defaultProps: { size: 24 },
          propsSchema: LUCIDE_PROPS_SCHEMA,
        }
      }}
      readOnly
    />
  )
}
